import os,json,re,subprocess,requests
from bs4 import BeautifulSoup
from sudachipy import tokenizer,dictionary
B='/home/horse/.openclaw/workspace/asanews';D='2026-09-28';T=dictionary.Dictionary().create();M=tokenizer.Tokenizer.SplitMode.C
PM={'名詞':'noun','動詞':'verb','助詞':'particle','形容詞':'adj','連体詞':'adj','副詞':'adverb','接続詞':'connector','接頭辞':'connector','接尾辞':'connector','助動詞':'grammar','感動詞':'connector'}
def hira(s):return ''.join(chr(ord(c)-96) if 'カ'<=c<='ン' else ('ゔ' if c=='ヴ' else c) for c in s)
def words(s):
 return [{'s':x.dictionary_form() if x.dictionary_form()!='*' else x.surface(),'r':hira(x.reading_form() or '') if hira(x.reading_form() or '')!=x.surface() else '','p':PM.get(x.part_of_speech()[0],'')} for x in T.tokenize(s,M)]
def fetch(h):
 b=BeautifulSoup(requests.get('https://news.yahoo.co.jp/articles/'+h,headers={'User-Agent':'Mozilla/5.0'}).text,'html.parser').select_one('div.article_body')
 return [p.get_text(' ',strip=True) for p in b.find_all('p') if p.get_text(strip=True) and not p.get_text(strip=True).startswith(('写真','【','FNN'))]
A=[
('naikaku-shijiritsu-45','内閣支持率45％に上昇、3カ月ぶり不支持率を逆転　世論調査','高市内閣の支持率が45％に上昇し、3カ月ぶりに不支持率を上回った。','46064192f4c390113f5fe74cc229dd928b40dc48',['The Takaichi Cabinet approval rating rose to 45 percent, while disapproval fell to 40 percent. Approval surpassed disapproval for the first time in three months.','The cabinet approval rating had declined from March, but the September 17 reshuffle appears to have led to a renewed rise.','The smartphone survey targeted people aged 18 or older and obtained 1,944 valid responses.'],['高市内阁支持率上升至45%，不支持率降至40%。支持率时隔三个月再次超过不支持率。','内阁支持率从3月开始下降，但9月17日的改组似乎带来了再次上升。','这项智能手机调查以18岁以上人士为对象，获得1944份有效回答。'],'「〜から…増」— 比…增加。例：前回から4ポイント増えた。\\n「〜ぶりに」— 时隔…再次。例：3カ月ぶりに逆転した。\\n「〜を対象とする」— 以…为对象。例：18歳以上を対象とする。',[['支持率','しじりつ','支持率'],['上昇','じょうしょう','上升'],['不支持率','ふしじりつ','不支持率'],['逆転','ぎゃくてん','逆转'],['世論調査','よろんちょうさ','民意调查'],['改造','かいぞう','改组']]),
('gunma-ota-satsujin-taiho','群馬・太田市 52歳女性殺害　長女の元夫を逮捕','群馬県太田市の住宅で女性が殺害された事件で、公開手配されていた長女の元夫が逮捕された。','1fb731c7278ceae0cbb34bb06f7094967a8f9933',['A woman was murdered at a home in Ota, Gunma, and her daughter’s former husband, who was wanted publicly, was arrested.','The woman was killed with a blade and her son was injured. Police found the suspect at a pachinko parlor in Takasaki and arrested him on suspicion of attempted murder.','The suspect fled on foot wearing only socks and changed clothes. He admitted the allegations; police will investigate the motive, including reported domestic violence.'],['群马县太田市一住宅的女性被杀，被公开通缉的长女前夫被逮捕。','女性被刀具杀害，儿子受伤。警方在高崎市一家柏青哥店找到嫌疑人，并以杀人未遂嫌疑逮捕他。','嫌疑人只穿袜子逃跑后换了衣服。他承认嫌疑，警方将调查包括家庭暴力在内的动机。'],'「〜に対する」— 对于…。例：長男に対する殺人未遂。\\n「〜ところを」— 正当…的时候。例：座っていたところを見つけた。\\n「〜ことから」— 由于…、鉴于…。例：被害を訴えていたことから追及する。',[['殺害','さつがい','杀害'],['公開手配','こうかいてはい','公开通缉'],['容疑者','ようぎしゃ','嫌疑人'],['身柄を確保する','みがらをかくほする','控制住人身'],['逃走','とうそう','逃跑'],['動機','どうき','动机']]),
('taifuu26-kanto-ooame','台風26号と秋雨前線の影響で関東再び大雨の恐れ','台風26号と秋雨前線の影響で、週後半に関東で再び大雨となる恐れがある。','a644632b24376074fbb2bea994a9d9a7a0899562',['Typhoon No. 26 and the autumn rain front may bring heavy rain to Kanto again in the latter half of the week.','The stalled front brought locally intense rain to Kyushu, and rain is expected across a wide area on the 28th. Thunderstorms are possible in Kanto.','The typhoon will activate the front with moist air. Heavy rain may return around October 1, so strict caution against landslides is needed.'],['台风26号和秋雨锋可能在下半周给关东再次带来大雨。','滞留的锋面给九州带来局部强降雨，预计28日大范围降雨，关东可能有雷雨。','台风带来的湿空气将使锋面活跃。10月1日前后可能再次大雨，需严防山体滑坡。'],'「〜の影響で」— 由于…的影响。例：台風の影響で雨が降る。\\n「〜恐れがある」— 有…的可能。例：大雨となる恐れがある。\\n「〜を通じて」— 整个…期间。例：一日を通じて雨となる。',[['秋雨前線','あきさめぜんせん','秋雨锋'],['停滞する','ていたいする','停滞'],['局地的','きょくちてき','局部的'],['雷雨','らいう','雷雨'],['土砂災害','どしゃさいがい','土砂灾害'],['厳重な警戒','げんじゅうなけいかい','严密警戒']])]
new=[]
for slug,title,sub,h,ens,lits,gram,voc in A:
 ps=fetch(h)[-3:]; pars=[]
 for i,ja in enumerate(ps):
  ap=f'assets/audio/{slug}/p{i+1}.mp3';os.makedirs(os.path.dirname(B+'/'+ap),exist_ok=True);subprocess.run(['edge-tts','--voice','ja-JP-NanamiNeural','--text',ja,'--write-media',B+'/'+ap],capture_output=True,timeout=180)
  pars.append({'id':f'p{i+1}','ja':ja,'en':ens[i],'literal':lits[i],'grammar':gram,'vocab':voc,'words':words(ja),'audio':ap})
 json.dump([{'id':slug,'title':title,'subtitle':sub,'level':'中級','length':len(pars),'date':D,'paragraphs':pars}],open(f'{B}/assets/readings/{slug}.json','w'),ensure_ascii=False,indent=2)
 open(f'{B}/_posts/{D}-{slug}.md','w').write(f'---\ntitle: {title}\ndate: {D} 07:00:00 +0900\ncategories: [ニュース]\ntags: [ニュース]\n---\n\n'+'\n\n'.join(p['ja'] for p in pars)+f'\n\n<a href="/asanews/reading-room/?read={slug}">📖 読解ルームで詳しく読む</a>\n')
 new.append({'id':slug,'title':title,'level':'中級','length':len(pars),'date':D,'file':f'assets/readings/{slug}.json'})
old=json.load(open(f'{B}/assets/readings/index.json'));ids={x['id'] for x in new};allx=new+[x for x in old if x['id'] not in ids];json.dump(allx,open(f'{B}/assets/readings/index.json','w'),ensure_ascii=False,indent=2)
jp=f'{B}/assets/js/reading-room.js';js=open(jp).read();ls=',\\n'.join("    { id: '%s', title: '%s', kicker: '中級', desc: '', badge: '%s段落', file: '/asanews/%s' }"%(x['id'],x['title'].replace("'","\\'"),x['length'],x['file']) for x in allx);open(jp,'w').write(re.sub(r'const READING_LIST = \\[.*?\\];','const READING_LIST = [\\n'+ls+'\\n    ];',js,flags=re.S));print('processed',','.join(x['id'] for x in new))
